define([
  "app/onem2m-ui/js/services/alert.service",
  "app/onem2m-ui/js/services/datastore-onem2m-data-adaptor.service",
  "app/onem2m-ui/js/services/datastore.service",
  "app/onem2m-ui/js/services/nx.service",
  "app/onem2m-ui/js/services/onem2m-crud.service",
  "app/onem2m-ui/js/services/onem2m-description.service",
  "app/onem2m-ui/js/services/onem2m-helper.service",
  "app/onem2m-ui/js/services/onem2m-input-component.service",
  "app/onem2m-ui/js/services/topology-helper.service",
  "app/onem2m-ui/js/services/topology.service",
  "app/onem2m-ui/js/services/tree-layout.service"
]);
